version: "3.4"
services:
  go:
    container_name: tfdbdriver
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    restart: on-failure