version: "3.8"
services:
  app:
    container_name: tfapi_prod
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    ports: 
      - 8888:8888 
    env_file:
      - .env
    restart: on-failure
    environment:
      - DOMAIN_NAME=tapfunds.net
    networks:
      - tapfunds
      
  client:
    stdin_open: true
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '1337:80'
    volumes:
      - "/app/node_modules"
      - "./:/app"


# Networks to be created to facilitate communication between containers
networks:
  tapfunds:
    driver: bridge