version: "3.8"

services:

  plaid:
    container_name: 
      plaid_service
    env_file:
      - ./plaid/.env 
    build:
      context: .
      dockerfile: ./plaid/Dockerfile.dev
    ports:
      - 8000:8000
    restart: 
      on-failure
    volumes:              # without this volume mapping to the directory of our project, live reloading wont happen
      - .:/usr/src/app
    networks:
      - tapfunds

# Networks to be created to facilitate communication between containers
networks:  
  tapfunds:
    driver: bridge