version: "3.8"

services:

  goauth:
    container_name: auth_service 
    env_file:
      - ./auth/.env
    build:
      context: .
      dockerfile: ./auth/Dockerfile.dev
    ports:
      - 8080:8080
    restart: on-failure
    volumes:              # without this volume mapping to the directory of our project, live reloading wont happen
      - .:/usr/src/app
    networks:
      - tapfunds

  client:
    container_name: client_service
    stdin_open: true
    env_file:
      - ./tfclient/.env
    build:
      context: .
      dockerfile: ./tfclient/Dockerfile.dev
    ports:
      - 80:80
    restart: on-failure
    volumes:              # without this volume mapping to the directory of our project, live reloading wont happen
      - .:/usr/src/app/
    networks:
      - tapfunds

# Networks to be created to facilitate communication between containers
networks:  
  tapfunds:
    driver: bridge