version: "3.4"
services:
  go:
    container_name: tfdbdriver
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/usr/src/opt/src/driver
    depends_on:
      - postgres
    networks:
      - tf

  postgres:
    image: postgres:latest
    container_name: tfdb
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - "5432:5432"
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - tf

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    ports:
      - "5050:80"
    networks:
      - tf
    restart: unless-stopped

volumes:
  api:
  database_postgres:

# Networks to be created to facilitate communication between containers
networks:
  tf:
    driver: bridge