kind: Deployment
apiVersion: apps/v1
metadata:
  name: tfapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tf
      tier: backend
      track: development
  template:
    metadata:
      labels:
        app: tf
        tier: backend
        track: development
    spec:
      containers:
        - name: tfapi
          image: qweliant/tfapi_go
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
      restartPolicy: Always