ARG ALPINE_VERSION=latest

FROM golang:1.15.5-alpine AS builder

RUN apk update && apk add --no-cache git
RUN mkdir -p /go/src/github.com/tapfunds/tf/plaid 
RUN mkdir /build
ADD /objectmapper /go/src/github.com/tapfunds/tf/plaid/ 
WORKDIR /go/src/github.com/tapfunds/tf/plaid 


RUN CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -tags seabolt_static -o /app main.go 

# Create alpine runtime image
FROM alpine:${ALPINE_VERSION} as app

COPY --from=builder /app /app

USER 1000

EXPOSE 8000

ENTRYPOINT ["/app"]