FROM python:3.8-alpine AS builder

ARG SEABOLT_VERSION=v1.7.4

RUN apk add --update --no-cache cmake make g++ openssl-dev openssl-libs-static git curl pkgconfig libcap
RUN git clone -b ${SEABOLT_VERSION} https://github.com/neo4j-drivers/seabolt.git /seabolt

WORKDIR /seabolt/build

RUN cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_LIBDIR=lib .. && cmake --build . --target install


COPY ./objectmapper/requirements/requirements.txt ./objectmapper/requirements/requirements.txt
RUN pip3 install -r objectmapper/requirements/requirements.txt

USER 1000

EXPOSE 1738


COPY ./objectmapper /app

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "1738"]