FROM python:3.9-alpine AS base

ARG SEABOLT_VERSION=v1.7.4

RUN apk add --update --no-cache cmake make g++ openssl-dev openssl-libs-static git curl pkgconfig libcap
RUN git clone -b ${SEABOLT_VERSION} https://github.com/neo4j-drivers/seabolt.git /seabolt


WORKDIR /seabolt/build

RUN cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_LIBDIR=lib .. && cmake --build . --target install

WORKDIR /app

FROM base as builder
     
RUN pip install fastapi uvicorn requests neomodel graphene

COPY ./objectmapper .

USER 1000
EXPOSE 1738

CMD ["uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "1738"]